steps:
  - id: 'decrypt secrets file'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=src/secrets.enc
      - --plaintext-file=src/secrets.ts
      - --location=global
      - --keyring=spotify-app-keyring
      - --key=first-key

  - id: 'install deps'
    name: 'node:18'
    entrypoint: 'yarn'
    args: [ 'install']

  - id: 'migrate'
    name: 'node:18'
    entrypoint: 'yarn'
    args: [ 'run', 'migrate']
    env: ['IS_CLOUD=1', 'PG_HOST=${_PG_HOST}']

  - id: 'compile typescript'
    name: 'node:18'
    entrypoint: 'yarn'
    args: [ 'run', 'compile-ts']

  - id: 'move package json'
    name: 'bash'
    args: ['cp', 'package.json', './dist']

  - id: 'build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'spotify-api:$COMMIT_SHA', '.', '--build-arg', 'PG_HOST=${_PG_HOST}' ]

  - id: 'tag docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'tag', 'spotify-api:$COMMIT_SHA', 'northamerica-northeast2-docker.pkg.dev/spotify-application-356414/spotify-api/spotify-api:$COMMIT_SHA']

  - id: 'push docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'northamerica-northeast2-docker.pkg.dev/spotify-application-356414/spotify-api/spotify-api:$COMMIT_SHA']

  - id: 'deploy image'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'spotify-api', '--image', 'northamerica-northeast2-docker.pkg.dev/spotify-application-356414/spotify-api/spotify-api:$COMMIT_SHA', '--region', 'northamerica-northeast2', '--memory', '128Mi', '--port', '3030', '--allow-unauthenticated', '--cpu-throttling']
