steps:
  # Step 1
  - id: 'decrypt secrets file'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=src/secrets.enc
      - --plaintext-file=src/secrets.ts
      - --location=global
      - --keyring=spotify-app-keyring
      - --key=first-key

  - id: 'decrypt tf sa creds'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=terraform/keys/tf-sa-key.enc
      - --plaintext-file=terraform/keys/tf-sa-key.json
      - --location=global
      - --keyring=spotify-app-keyring
      - --key=first-key

  - id: 'install deps'
    name: 'node:18'
    entrypoint: 'yarn'
    args: [ 'install']

  - id: 'compile typescript'
    name: 'node:18'
    entrypoint: 'yarn'
    args: [ 'run', 'compile-ts']

  - id: 'move package json'
    name: 'bash'
    args: ['cp', 'package.json', './dist']

  - id: 'tf init'
    name: 'hashicorp/terraform:1.2.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          cd terraform      
          terraform init
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.2.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          cd terraform      
          terraform apply -auto-approve
