steps:
  - id: 'decrypt secrets file'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=src/secrets.enc
      - --plaintext-file=src/secrets.ts
      - --location=global
      - --keyring=spotify-app-keyring
      - --key=first-key

  - id: 'install deps'
    name: 'node:18'
    entrypoint: 'yarn'
    args: [ 'install']

  - id: 'migrate'
    name: 'node:18'
    entrypoint: 'yarn'
    args: [ 'run', 'migrate']
    env: ['IS_CLOUD=1', 'PG_HOST=${_PG_HOST}']

  - id: 'compile typescript'
    name: 'node:18'
    entrypoint: 'yarn'
    args: [ 'run', 'compile-ts']

  - id: 'move package json'
    name: 'bash'
    args: ['cp', 'package.json', './dist']

  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    dir: dist
    args:
      - functions
      - deploy
      - spotify-api
      - --region=us-central1
      - --allow-unauthenticated
      - --entry-point=main
      - --runtime=nodejs16
      - --memory=128
      - --trigger-http
      - --timeout=180
      - --set-env-vars=REDIRECT_URI=https://us-central1-spotify-application-356414.cloudfunctions.net/spotify-api/oauth_callback,FRONT_END_HOST=https://spotify-frontend-wgvygz45ba-pd.a.run.app,PG_HOST=${_PG_HOST},IS_CLOUD=1
